import React from 'react';
import { ProcurementWorkflow, SystemSettings, ProcurementStatus } from '../types';

interface DocumentTemplateProps {
  type: 'GSRF' | 'PRF' | 'PO' | 'PEF' | 'CERT';
  data: ProcurementWorkflow;
  settings?: SystemSettings | null;
}

export const DocumentTemplate: React.FC<DocumentTemplateProps> = ({ type, data, settings }) => {
  const currentYear = new Date().getFullYear();
  const isService = data.requestType === 'SERVICE';

  const renderHeader = (title: string, refNo: string) => (
    <div className="flex flex-col mb-6 border-b-2 border-black pb-4">
      <div className="flex justify-between items-start w-full relative min-h-[80px]">
        {settings?.templateConfig?.showLogo && settings?.logoUrl && (
           <div className="w-24 h-20 flex items-center justify-center flex-shrink-0">
             <img src={settings.logoUrl} alt="Logo" className="max-w-full max-h-full object-contain" />
           </div>
        )}
        <div className="flex-1 text-right pl-4">
          <h1 className="text-xl font-bold uppercase tracking-wider mb-1 font-serif">
              {settings?.officeName || 'Government Entity of State'}
          </h1>
          <h2 className="text-sm uppercase text-slate-700 mb-1 font-serif">
              {settings?.departmentName || 'Department of Administration & Finance'}
          </h2>
          <div className="text-[10px] text-slate-600 leading-tight">
             <p className="whitespace-pre-line">{settings?.officeAddress || 'Address Not Configured'}</p>
             <div className="mt-1 flex flex-wrap justify-end gap-x-3">
                {settings?.phone && <span>Tel: {settings.phone}</span>}
                {settings?.email && <span>Email: {settings.email}</span>}
                {settings?.website && <span>Web: {settings.website}</span>}
                {settings?.taxId && <span>Tax ID: {settings.taxId}</span>}
             </div>
          </div>
        </div>
      </div>
      <div className="w-full flex justify-between items-end mt-4 pt-2 border-t border-slate-200">
        <div>
          <p className="text-xs font-bold uppercase tracking-wide text-gov-800">Official Document: {title}</p>
        </div>
        <div className="text-right">
          <p className="text-sm"><span className="font-bold uppercase text-[10px] text-slate-500 block">Reference Number</span> {refNo}</p>
          <p className="text-[10px] text-slate-500 font-bold uppercase mt-1">Date: {new Date().toLocaleDateString()}</p>
        </div>
      </div>
    </div>
  );

  const renderCustomBlocks = () => {
      if (!settings?.templateConfig?.customBlocks || settings.templateConfig.customBlocks.length === 0) return null;
      
      return (
          <div className="mt-8 pt-4 border-t-2 border-dashed border-slate-300">
              {settings.templateConfig.customBlocks.map(block => (
                  <div key={block.id} className="mb-4">
                      {block.type === 'title' && <h3 className="text-lg font-bold uppercase mb-2">{block.content}</h3>}
                      {block.type === 'text' && <p className="text-xs text-slate-700 whitespace-pre-wrap">{block.content}</p>}
                      {block.type === 'divider' && <hr className="border-black my-4" />}
                      {block.type === 'signature' && (
                          <div className="mt-8 pt-2 border-t border-black w-48">
                              <p className="text-xs font-bold uppercase">{block.content || 'Authorized Signature'}</p>
                          </div>
                      )}
                      {block.type === 'image' && (
                          <div className="h-24 w-24 bg-slate-100 flex items-center justify-center text-slate-400 border border-slate-300">
                              IMG
                          </div>
                      )}
                  </div>
              ))}
          </div>
      );
  };

  const renderFooter = () => (
      <div className="mt-auto pt-8 border-t border-slate-300 text-center text-[9px] text-slate-500">
          <p>{settings?.templateConfig?.footerText || 'System Generated Document'}</p>
          <p className="mt-1">Generated by GovTrack System • {new Date().toLocaleString()}</p>
      </div>
  );

  const renderSignatureBlock = (role: string, name: string | undefined, signature: string | undefined, date: string | undefined) => (
    <div className="flex-1 flex flex-col items-center">
      <div className="h-16 w-32 mb-1 flex items-end justify-center">
        {signature ? <img src={signature} alt="Signed" className="max-h-16 object-contain" /> : <div className="h-8"></div>}
      </div>
      <div className="w-32 border-t border-black pt-1 text-center">
        <p className="text-[10px] font-bold uppercase">{role}</p>
        <p className="text-[10px] truncate max-w-full">{name || '________________'}</p>
        <p className="text-[9px] text-slate-500">{date ? new Date(date).toLocaleDateString() : ''}</p>
      </div>
    </div>
  );

  // --- Completion Certificate (CERT) ---
  if (type === 'CERT' && data.certificate) {
    const c = data.certificate;
    const vendorName = data.quotations?.find(q => q.selected)?.vendorName || 'Selected Vendor';
    const totalPrice = data.serviceCompletionDetails?.totalCost || data.quotations?.find(q => q.selected)?.price || 0;

    return (
        <div className="printable-area flex flex-col text-black font-sans">
            {renderHeader('COMPLETION CERTIFICATE', c.certificateNumber)}
            
            <div className="text-center my-8">
                <h2 className="text-2xl font-bold uppercase underline tracking-widest font-serif">Certificate of Completion</h2>
            </div>

            <div className="space-y-6 text-sm leading-relaxed">
                <p>This is to certify that the following work/service has been successfully completed to the satisfaction of <span className="font-bold">{settings?.officeName}</span>.</p>
                
                <div className="border border-black p-4 space-y-3 bg-slate-50">
                    <div className="grid grid-cols-3 gap-4">
                        <div className="font-bold text-slate-500 uppercase text-[10px]">Work Details:</div>
                        <div className="col-span-2 font-medium">{data.items.map(i => i.description).join(', ')}</div>
                    </div>
                    <div className="grid grid-cols-3 gap-4 border-t border-slate-200 pt-2">
                        <div className="font-bold text-slate-500 uppercase text-[10px]">Work Performed by:</div>
                        <div className="col-span-2 font-bold text-gov-800">{vendorName}</div>
                    </div>
                    <div className="grid grid-cols-3 gap-4 border-t border-slate-200 pt-2">
                        <div className="font-bold text-slate-500 uppercase text-[10px]">Awarded by:</div>
                        <div className="col-span-2">{settings?.officeName}</div>
                    </div>
                    <div className="grid grid-cols-3 gap-4 border-t border-slate-200 pt-2">
                        <div className="font-bold text-slate-500 uppercase text-[10px]">Agreement / Contract #:</div>
                        <div className="col-span-2 font-mono">{c.agreementNumber}</div>
                    </div>
                </div>

                <div className="grid grid-cols-2 gap-8 py-4">
                    <div className="space-y-2">
                        <div className="flex justify-between border-b border-slate-200 pb-1">
                            <span className="text-[10px] font-bold text-slate-500">Awarded Date:</span>
                            <span>{new Date(c.awardedDate).toLocaleDateString()}</span>
                        </div>
                        <div className="flex justify-between border-b border-slate-200 pb-1">
                            <span className="text-[10px] font-bold text-slate-500">Started Date:</span>
                            <span>{c.startedDate ? new Date(c.startedDate).toLocaleDateString() : 'N/A'}</span>
                        </div>
                        <div className="flex justify-between border-b border-slate-200 pb-1">
                            <span className="text-[10px] font-bold text-slate-500">Completed Date:</span>
                            <span>{new Date(c.completionDate).toLocaleDateString()}</span>
                        </div>
                    </div>
                    <div className="space-y-2">
                        <div className="flex justify-between border-b border-slate-200 pb-1">
                            <span className="text-[10px] font-bold text-slate-500">Duration:</span>
                            <span>{c.duration || 'N/A'}</span>
                        </div>
                        <div className="flex justify-between border-b border-slate-200 pb-1">
                            <span className="text-[10px] font-bold text-slate-500">Total Price:</span>
                            <span className="font-bold">MVR {totalPrice.toFixed(2)}</span>
                        </div>
                        <div className="flex justify-between border-b border-slate-200 pb-1">
                            <span className="text-[10px] font-bold text-slate-500">Document Date:</span>
                            <span>{new Date(c.documentDate).toLocaleDateString()}</span>
                        </div>
                    </div>
                </div>

                <div className="space-y-2 pt-4">
                    <p className="text-[10px] font-bold text-slate-500 uppercase">Amount in Words:</p>
                    <p className="italic font-medium border border-slate-200 p-2 rounded bg-slate-50">{c.totalPriceInWords}</p>
                </div>

                {c.additionalNotes && (
                    <div className="space-y-2 pt-4">
                        <p className="text-[10px] font-bold text-slate-500 uppercase">Additional Notes / Observations:</p>
                        <p className="text-xs whitespace-pre-wrap">{c.additionalNotes}</p>
                    </div>
                )}
            </div>

            <div className="mt-16 flex justify-end">
                <div className="w-64 text-center">
                    <div className="h-20 flex items-end justify-center mb-1">
                        {c.managerSignature ? (
                            <img src={c.managerSignature} alt="Signed" className="max-h-20 object-contain" />
                        ) : (
                            <div className="h-1 bg-slate-300 w-full mb-2"></div>
                        )}
                    </div>
                    <div className="border-t border-black pt-2">
                        <p className="text-xs font-bold uppercase">Authorized Signatory (Manager)</p>
                        <p className="text-sm">{c.managerName || '________________________'}</p>
                        <p className="text-[10px] text-slate-500">{settings?.officeName}</p>
                    </div>
                </div>
            </div>

            {renderCustomBlocks()}
            {renderFooter()}
        </div>
    );
  }

  // --- Goods & Services Requisition Form (GSRF) ---
  if (type === 'GSRF') {
    const isGoods = data.requestType === 'GOODS';
    const isIssued = data.status === ProcurementStatus.ISSUED || data.status === ProcurementStatus.COMPLETED || data.status === ProcurementStatus.PO_ISSUED;
    
    return (
      <div className="printable-area flex flex-col text-black font-sans">
        {renderHeader(isGoods ? 'GOODS REQUISITION FORM' : 'SERVICE REQUISITION FORM', data.gsrfRefNumber || `GSRF/${currentYear}/PENDING`)}
        
        <div className="mb-6 grid grid-cols-2 gap-x-8 gap-y-2 text-xs">
          <div><span className="font-bold block">Requesting Section:</span> {data.section || data.requesterDepartment}</div>
          <div><span className="font-bold block">Required By Date:</span> {data.requiredDate ? new Date(data.requiredDate).toLocaleDateString() : 'N/A'}</div>
          <div className="col-span-2 mt-2">
              <span className="font-bold block">{isGoods ? 'Purpose / Remarks:' : 'Work Scope / Description of Problem:'}</span> 
              <div className="border border-slate-300 p-2 min-h-[40px] rounded bg-slate-50">{data.remarks || 'N/A'}</div>
          </div>
          {isGoods && data.issueDetails && (
            <div className="col-span-2 border-t border-slate-300 pt-2 mt-2">
                <span className="font-bold">Issue Status:</span> <span className="text-green-800 font-semibold">ISSUED</span> to {data.issueDetails.receiverName} on {new Date(data.issueDetails.issueDate).toLocaleDateString()}
            </div>
          )}
          {!isGoods && data.assessmentDetails && (
             <div className="col-span-2 border-t border-slate-300 pt-2 mt-2">
                <span className="font-bold">Technical Findings:</span> <span className="text-slate-700">{data.assessmentDetails.findings}</span>
            </div>
          )}
        </div>

        <table className="w-full border-collapse border border-black mb-6 text-xs">
          <thead>
            <tr className="bg-slate-100">
              <th className="border border-black p-2 w-12">#</th>
              <th className="border border-black p-2 text-left">{isGoods ? 'Item Description' : 'Service Task / Requirement'}</th>
              <th className="border border-black p-2 w-20">{isGoods ? 'Req Qty' : 'Qty'}</th>
              {isGoods && <th className="border border-black p-2 w-20">Issued</th>}
              <th className="border border-black p-2">Notes</th>
            </tr>
          </thead>
          <tbody>
            {data.items.map((item, idx) => (
              <tr key={idx}>
                <td className="border border-black p-2 text-center">{idx + 1}</td>
                <td className="border border-black p-2">{item.description}</td>
                <td className="border border-black p-2 text-center font-bold">{item.quantity}</td>
                {isGoods && <td className="border border-black p-2 text-center">{isIssued ? item.quantity : ''}</td>}
                <td className="border border-black p-2"></td>
              </tr>
            ))}
            {[...Array(Math.max(0, 8 - data.items.length))].map((_, i) => (
               <tr key={`empty-${i}`} className="h-8">
                <td className="border border-black"></td>
                <td className="border border-black"></td>
                <td className="border border-black"></td>
                {isGoods && <td className="border border-black"></td>}
                <td className="border border-black"></td>
               </tr>
            ))}
          </tbody>
        </table>

        <div className="flex justify-between mt-8 gap-2">
          {renderSignatureBlock('REQUESTED BY', data.requesterName, data.requesterSignature, data.requestDate)}
          {renderSignatureBlock('SECTION HEAD', 'Supervisor', undefined, undefined)}
          {renderSignatureBlock(isGoods ? 'STOCK KEEPER' : 'TECHNICAL OFFICER', isGoods ? 'Stores Officer' : 'Maintenance Lead', data.stockKeeperSignature, data.stockCheckDate)}
          {renderSignatureBlock('RECEIVED BY / VERIFIED BY', data.issueDetails?.receiverName || data.serviceCompletionDetails?.verifiedBy || 'Authorized Party', undefined, data.issueDetails?.issueDate || data.serviceCompletionDetails?.completionDate)}
        </div>
        
        {renderCustomBlocks()}
        {renderFooter()}
      </div>
    );
  }

  // --- Purchase Request Form (PRF) ---
  if (type === 'PRF') {
     return (
      <div className="printable-area flex flex-col text-black font-sans">
        {renderHeader(isService ? 'SERVICE REQUEST FORM' : 'PURCHASE REQUEST FORM', data.prRefNumber || `${isService ? 'SR' : 'PR'}/${currentYear}/PENDING`)}
        
        <div className="mb-6 grid grid-cols-2 gap-x-8 gap-y-2 text-xs">
           <div><span className="font-bold">{isService ? 'SRF' : 'GSRF'} Reference:</span> {data.gsrfRefNumber || 'N/A'}</div>
           <div><span className="font-bold">Date Raised:</span> {new Date().toLocaleDateString()}</div>
           <div className="col-span-2 border-b border-black pb-2 mb-2"></div>
           <div><span className="font-bold">Department:</span> {data.section || data.requesterDepartment}</div>
           <div><span className="font-bold">Required Date:</span> {data.requiredDate ? new Date(data.requiredDate).toLocaleDateString() : 'N/A'}</div>
        </div>

        <table className="w-full border-collapse border border-black mb-8 text-xs">
          <thead>
            <tr className="bg-slate-100">
              <th className="border border-black p-2 w-12">#</th>
              <th className="border border-black p-2 text-left">Description</th>
              {!isService && <th className="border border-black p-2 w-24">In Stock</th>}
              <th className="border border-black p-2 w-24">{isService ? 'Quantity' : 'Purchase Qty'}</th>
            </tr>
          </thead>
          <tbody>
            {data.items.map((item, idx) => (
              <tr key={idx}>
                <td className="border border-black p-2 text-center">{idx + 1}</td>
                <td className="border border-black p-2">{item.description}</td>
                {!isService && <td className="border border-black p-2 text-center text-slate-500">0</td>}
                <td className="border border-black p-2 text-center font-bold">{item.quantity}</td>
              </tr>
            ))}
            {[...Array(Math.max(0, 8 - data.items.length))].map((_, i) => (
               <tr key={`empty-${i}`} className="h-8">
                <td className="border border-black"></td>
                <td className="border border-black"></td>
                {!isService && <td className="border border-black"></td>}
                <td className="border border-black"></td>
               </tr>
            ))}
          </tbody>
        </table>

         <div className="flex justify-between mt-12 gap-8">
          {renderSignatureBlock('PREPARED BY', isService ? 'Technical Officer' : 'Procurement Officer', data.stockKeeperSignature, data.stockCheckDate)}
          {renderSignatureBlock('VERIFIED BY', 'Finance Officer', undefined, undefined)}
          {renderSignatureBlock('AUTHORIZED BY', isService ? 'Maintenance Head' : 'Head of Procurement', data.authorizedBySignature, undefined)}
        </div>
        
        {renderCustomBlocks()}
        {renderFooter()}
      </div>
     );
  }

  // --- Price Evaluation Form (PEF) ---
  if (type === 'PEF') {
    // Single Source
    if (data.evaluationType === 'SINGLE_SOURCE') {
        return (
          <div className="printable-area flex flex-col text-black font-sans">
             {renderHeader('SINGLE SOURCE JUSTIFICATION', data.poNumber || 'PENDING')}
             
             <div className="mb-6 space-y-4 text-xs">
                <div className="flex justify-between">
                    <div><span className="font-bold">Requesting Section:</span> {data.section || data.requesterDepartment}</div>
                    <div><span className="font-bold">{isService ? 'SR' : 'PR'} Ref No:</span> {data.prRefNumber}</div>
                </div>
                
                <div className="border border-black p-4 bg-slate-50 min-h-[100px]">
                    <p className="font-bold mb-2 uppercase text-[10px] text-slate-600">Justification for Single Source Procurement:</p>
                    <p className="italic text-sm">{data.singleSourceJustification}</p>
                </div>
                
                <div className="grid grid-cols-2 gap-6 pt-4">
                    <div className="border border-black p-3">
                        <p className="font-bold text-[10px] uppercase text-slate-500">Selected Vendor / Contractor</p>
                        <p className="font-bold text-lg">{data.selectedVendor}</p>
                    </div>
                    <div className="border border-black p-3">
                        <p className="font-bold text-[10px] uppercase text-slate-500">Total Estimated Cost</p>
                        <p className="font-bold text-lg">MVR {(data.quotations?.[0]?.price || 0).toFixed(2)}</p>
                    </div>
                </div>
             </div>

             <div className="flex justify-between mt-12 gap-4">
                {renderSignatureBlock('REQUESTED BY', isService ? 'Technical Officer' : 'Procurement Officer', data.stockKeeperSignature, undefined)}
                {renderSignatureBlock('APPROVED BY', 'Director General', data.authorizedBySignature, undefined)}
            </div>
            
            {renderCustomBlocks()}
            {renderFooter()}
          </div>
        );
    }

    // Matrix Evaluation
    return (
      <div className="printable-area flex flex-col text-black font-sans">
        {renderHeader('PRICE EVALUATION FORM', data.evalRefNumber || 'PENDING')}

        <div className="mb-4 grid grid-cols-3 gap-4 text-xs">
          <div><span className="font-bold">Dept:</span> {data.section || data.requesterDepartment}</div>
          <div><span className="font-bold">Method:</span> {data.evaluationMethod}</div>
          <div><span className="font-bold">{isService ? 'SR' : 'PR'} Ref:</span> {data.prRefNumber}</div>
        </div>

        {data.evaluationType === 'QUOTATION' ? (
           // Quotation Based Table
           <table className="w-full border-collapse border border-black mb-6 text-xs">
             <thead>
               <tr className="bg-slate-100">
                 <th className="border border-black p-2 w-10">#</th>
                 <th className="border border-black p-2 text-left">Vendor Name</th>
                 <th className="border border-black p-2 w-24">Quote No</th>
                 <th className="border border-black p-2 w-24">Date</th>
                 <th className="border border-black p-2 w-28 text-right">Total (MVR)</th>
               </tr>
             </thead>
             <tbody>
                {data.quotations?.map((q, idx) => (
                    <tr key={idx} className={q.selected ? "bg-green-50" : ""}>
                        <td className="border border-black p-2 text-center">{idx + 1}</td>
                        <td className="border border-black p-2 font-medium">
                            {q.vendorName}
                            {q.selected && <span className="block text-[9px] font-bold text-green-700 mt-1">[RECOMMENDED]</span>}
                        </td>
                        <td className="border border-black p-2 text-center">{q.quoteNumber || '-'}</td>
                        <td className="border border-black p-2 text-center">{q.quoteDate ? new Date(q.quoteDate).toLocaleDateString() : '-'}</td>
                        <td className="border border-black p-2 text-right font-mono font-bold">{(q.price || 0).toFixed(2)}</td>
                    </tr>
                ))}
             </tbody>
           </table>
        ) : (
           // Form Based Table (Item Matrix)
           <table className="w-full border-collapse border border-black mb-6 text-[10px]">
            <thead>
                <tr className="bg-slate-100">
                <th className="border border-black p-1 w-8">#</th>
                <th className="border border-black p-1 text-left">Description</th>
                <th className="border border-black p-1 w-12">Qty</th>
                {data.quotations?.map((q, i) => (
                    <th key={i} className="border border-black p-1 w-24">
                        <div className="font-bold truncate">{q.vendorName || `Vendor ${i+1}`}</div>
                        <div className="font-normal text-[9px]">Unit Price</div>
                    </th>
                )) || <th className="border border-black p-1">Vendor Details</th>}
                </tr>
            </thead>
            <tbody>
                {data.items.map((item, idx) => (
                <tr key={idx}>
                    <td className="border border-black p-1 text-center">{idx + 1}</td>
                    <td className="border border-black p-1">{item.description}</td>
                    <td className="border border-black p-1 text-center">{item.quantity}</td>
                    {data.quotations?.map((q, i) => (
                    <td key={i} className="border border-black p-1 text-center">
                        {q.price > 0 ? `${q.price.toFixed(2)}` : '-'}
                    </td>
                    ))}
                </tr>
                ))}
                <tr className="font-bold bg-slate-50 border-t-2 border-black">
                    <td colSpan={3} className="border border-black p-1 text-right">TOTAL (MVR)</td>
                    {data.quotations?.map((q, i) => (
                    <td key={i} className={`border border-black p-2 text-center ${q.selected ? 'bg-green-100' : ''}`}>
                        {q.price > 0 ? `${(q.price * (data.items[0]?.quantity || 1)).toFixed(2)}` : '-'}
                        {q.selected && <div className="text-[9px] text-green-800">RECOMMENDED</div>}
                    </td>
                    ))}
                </tr>
            </tbody>
            </table>
        )}

        <div className="mt-4 mb-4 text-xs border border-black p-3">
          <p className="font-bold mb-1 uppercase text-slate-500 text-[10px]">Recommendation / Committee Notes:</p>
          <p>
             Based on the evaluation above, it is recommended to award the contract to 
             <span className="font-bold underline mx-1">{data.quotations?.find(q => q.selected)?.vendorName}</span> 
             as they meet the technical requirements at the most competitive price.
          </p>
        </div>

        <div className="flex justify-between mt-auto pt-8 gap-4">
          {renderSignatureBlock('PREPARED BY', isService ? 'Technical Officer' : 'Procurement Officer', data.stockKeeperSignature, undefined)}
          {renderSignatureBlock('CHECKED BY', 'Finance Officer', undefined, undefined)}
          {renderSignatureBlock('APPROVED BY', 'Director', data.authorizedBySignature, undefined)}
        </div>
        
        {renderCustomBlocks()}
        {renderFooter()}
      </div>
    );
  }

  // --- Service Order (SO) or Purchase Order (PO) ---
  if (type === 'PO') {
     const selectedQuote = data.quotations?.find(q => q.selected);
     const totalAmount = selectedQuote ? selectedQuote.price : 0;
     const docTitle = isService ? 'SERVICE ORDER' : 'PURCHASE ORDER';
     const refLabel = isService ? 'SO' : 'PO';

     return (
       <div className="printable-area flex flex-col text-black font-sans">
         {renderHeader(docTitle, data.poNumber || 'PENDING')}
         
         <div className="flex justify-between mb-8 text-xs gap-8">
            <div className="w-1/2 border border-black p-3">
               <h3 className="font-bold uppercase mb-2 border-b border-black pb-1">{isService ? 'Contractor Details' : 'Vendor Details'}</h3>
               <p className="font-bold text-sm">{selectedQuote?.vendorName || 'N/A'}</p>
               <p className="text-slate-600">Quote Ref: {selectedQuote?.quoteNumber || 'N/A'}</p>
               {selectedQuote?.quoteDate && <p className="text-slate-600">Date: {new Date(selectedQuote.quoteDate).toLocaleDateString()}</p>}
            </div>
            <div className="w-1/2 border border-black p-3 bg-slate-50">
               <h3 className="font-bold uppercase mb-2 border-b border-black pb-1">{isService ? 'Service Details' : 'Order Details'}</h3>
               <p><span className="font-bold w-24 inline-block">{refLabel} Date:</span> {data.budgetVerifiedDate ? new Date(data.budgetVerifiedDate).toLocaleDateString() : new Date().toLocaleDateString()}</p>
               <p><span className="font-bold w-24 inline-block">Budget Code:</span> {data.budgetCode}</p>
               <p><span className="font-bold w-24 inline-block">{isService ? 'SR' : 'PR'} Ref:</span> {data.prRefNumber}</p>
               <p><span className="font-bold w-24 inline-block">Currency:</span> MVR</p>
            </div>
         </div>

         <table className="w-full border-collapse border border-black mb-4 text-xs">
           <thead>
             <tr className="bg-slate-100">
               <th className="border border-black p-2 w-12">#</th>
               <th className="border border-black p-2 text-left">Description</th>
               <th className="border border-black p-2 w-24">Qty</th>
             </tr>
           </thead>
           <tbody>
             {data.items.map((item, idx) => (
               <tr key={idx}>
                 <td className="border border-black p-2 text-center">{idx + 1}</td>
                 <td className="border border-black p-2">{item.description}</td>
                 <td className="border border-black p-2 text-center">{item.quantity}</td>
               </tr>
             ))}
             {/* Total Row */}
             <tr className="font-bold text-base">
                <td colSpan={2} className="border border-black p-3 text-right uppercase">Total Amount</td>
                <td className="border border-black p-3 text-right bg-slate-50">MVR {(totalAmount || 0).toFixed(2)}</td>
             </tr>
           </tbody>
         </table>

         <div className="text-xs border-t border-black pt-4 mt-4">
            <p className="font-bold uppercase text-[10px] text-slate-500 mb-2">Terms & Conditions:</p>
            <ol className="list-decimal ml-4 space-y-1 text-[10px] text-slate-700">
               <li>This {docTitle} number must appear on all invoices and correspondence.</li>
               <li>{isService ? 'Work completion' : 'Delivery'} must be made within the specified timeline. Late {isService ? 'completion' : 'delivery'} may result in penalties.</li>
               <li>{isService ? 'Services' : 'Goods'} must meet the quality standards specified in the solicitation documents.</li>
               <li>Payment will be processed within 30 days of receipt of invoice and satisfactory {isService ? 'service verification' : 'goods acceptance'}.</li>
            </ol>
         </div>

         <div className="flex justify-between mt-auto pt-12 gap-8">
           {renderSignatureBlock('PREPARED BY', isService ? 'Technical Officer' : 'Procurement Officer', data.stockKeeperSignature, undefined)}
           {renderSignatureBlock('AUTHORIZED BY', 'Finance Director', data.authorizedBySignature, data.budgetVerifiedDate)}
         </div>
         
         {renderCustomBlocks()}
         {renderFooter()}
       </div>
     );
  }

  return <div>Document template not found.</div>;
};